# -*- coding: utf-8 -*-
"""modified_iitmandi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXob2h74nTDClQTxZ_qaa49gG4mnamYM
"""

!pip install google-generativeai requests pandas fastapi uvicorn pyngrok

import google.generativeai as genai
genai.configure(api_key="AIzaSyBCeGDsx7lra2yuyUk0jy4iYfG0X1H_JKo")
model = genai.GenerativeModel("gemini-2.5-flash")
response = model.generate_content("Say Hello in one sentence.")
print(response.text)

import google.generativeai as genai
import requests, json, pandas as pd, time
from datetime import datetime
BASE_URL = "https://campaignx.inxiteout.ai"
CAMPAIGNX_KEY = "7ZSFMQrZPUYZa0KOtnJcxEH5PeUjWnp4dRi5N-FZ7SU"
GEMINI_KEY = "AIzaSyBCeGDsx7lra2yuyUk0jy4iYfG0X1H_JKo"
HEADERS = {"X-API-Key": CAMPAIGNX_KEY, "Content-Type": "application/json"}
# Configure Gemini once at startup
genai.configure(api_key=GEMINI_KEY)
gemini = genai.GenerativeModel("gemini-2.5-flash")

import requests
import re
import json
import pandas as pd
import time
from datetime import timedelta
from datetime import datetime

class MarketingAgent:

    def __init__(self):
        self.customers = []
        self.segmented_customers = []
        self.campaign_history = []
        self.iteration = 0

    def fetch_cohort(self):
        r = requests.get(f"{BASE_URL}/api/v1/get_customer_cohort", headers=HEADERS)
        print(f"Cohort API Status: {r.status_code}")

        resp = r.json()

        # Handle list response directly
        if isinstance(resp, list):
            self.customers = resp

        # Handle dict response with various key names
        elif isinstance(resp, dict):
            self.customers = (
                resp.get("data")
                or resp.get("customers")
                or resp.get("cohort")
                or resp.get("results")
                or []
            )

            if not self.customers:
                print("WARNING: No customers found. Keys:", list(resp.keys()))
                print("Full response:", resp)

        else:
            self.customers = []
            print("WARNING: Unexpected response type:", type(resp))

        print(f"Fetched {len(self.customers)} customers")
        return self.customers

    def parse_brief(self, brief: str) -> dict:
        self.campaign_brief = brief

        prompt = f"""
You are a marketing strategist. Parse this campaign brief and extract:

1. product_name: name of the product
2. usps: list of unique selling points
3. target_segments: specific audience segments mentioned
4. optimization_goal: open rate / click rate / both
5. special_instructions: any constraints (e.g. don't skip inactive)
6. cta_url: the call-to-action URL

Campaign Brief: {brief}

IMPORTANT: Return ONLY valid JSON. No markdown, no explanation.
"""
        time.sleep(3)
        response = gemini.generate_content(prompt)

        raw = response.text.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(raw)

        print("Brief parsed:", json.dumps(parsed, indent=2))
        return parsed

    def segment_customers(self, parsed_brief):
        target = parsed_brief.get("target_segments", [])
        segment = []

        for c in self.customers:
            age = c.get("age", 0)
            gender = c.get("gender", "").lower()

            if "female senior citizens" in str(target).lower():
                if gender == "female" and age >= 60:
                    segment.append(c)

        if not segment:
            segment = self.customers

        print(f"Segment selected: {len(segment)} customers")
        return segment

    def generate_strategy(self, parsed_brief, performance_data=None) -> dict:

        perf_ctx = ""

        if performance_data:
            perf_ctx = f"""
Previous campaign performance:
- Open Rate : {performance_data['open_rate']}%
- Click Rate: {performance_data['click_rate']}%
- Assessment: {performance_data.get('assessment', 'N/A')}
- Insights  : {performance_data.get('insights', 'N/A')}

Use these insights to improve the next campaign strategy.
"""

        prompt = f"""
You are a senior digital marketing expert specialising in financial products.

Generate an email campaign strategy based on:

Product Brief : {json.dumps(parsed_brief)}
Customer Count : {len(self.segmented_customers)} customers
Campaign Iter : {self.iteration + 1}
Today's Date : {datetime.now().strftime('%d:%m:%y')}

{perf_ctx}

Generate strategy with:

- subject: catchy email subject (max 200 chars, can use emojis)
- body: full email body (max 5000 chars, engaging, persuasive, and optimized for high open and click rate).

The email body MUST follow these rules:

1. It should be conversational and persuasive.
2. It should clearly explain the benefits of the product.
3. It should encourage customers to take action.

At the end of the email, you MUST include this CTA exactly like this:

Explore XDeposit now:
{parsed_brief["cta_url"]}

Do not change this URL.

- send_time: optimal send time tomorrow in format DD:MM:YY HH:MM:SS
- rationale: brief explanation of strategic choices made

IMPORTANT:
Return ONLY valid JSON. No markdown. No explanation outside JSON.

Format:
{{"variant_a":{{"subject":"...","body":"..."}},"variant_b":{{"subject":"...","body":"..."}},"send_time":"DD:MM:YY HH:MM:SS","rationale":"..."}}
"""

        time.sleep(3)
        response = gemini.generate_content(prompt)

        raw = response.text.replace("```json", "").replace("```", "").strip()

        strategy = json.loads(raw)
        variant_a = strategy["variant_a"]
        variant_b = strategy["variant_b"]

        strategy["variants"] = [variant_a, variant_b]

        for v in strategy["variants"]:
            if parsed_brief["cta_url"] not in v["body"]:
                v["body"] += f"\n\nExplore XDeposit now:\n{parsed_brief['cta_url']}"

        print(f"Strategy ready. Variant A Subject: {strategy['variants'][0]['subject'][:60]}...")
        return strategy

    def split_for_ab_test(self):

        customers = self.segmented_customers

        if len(customers) < 2:
            return customers, customers

        half = len(customers) // 2

        group_a = customers[:half]
        group_b = customers[half:]

        return group_a, group_b

    def human_approval(self, strategy: dict) -> bool:

        print("\n" + "=" * 65)
        print(" HUMAN REVIEW REQUIRED — Approve before campaign sends")
        print("=" * 65)

        print(f" Send Time: {strategy['send_time']}")
        print(f" Rationale: {strategy['rationale']}")

        print("\n Variant A Subject:")
        print(strategy["variants"][0]["subject"])

        print("\n Variant A Body Preview:")
        print(strategy["variants"][0]["body"][:500])

        print("\n Variant B Subject:")
        print(strategy["variants"][1]["subject"])

        print("\n Variant B Body Preview:")
        print(strategy["variants"][1]["body"][:500])

        print("=" * 65)

        decision = input("\n Approve campaign? (yes/no): ").strip().lower()

        return decision == "yes"

    def send_campaign(self, strategy: dict) -> str:
        customer_ids = [c["customer_id"] for c in self.segmented_customers]
        payload = {
            "subject": strategy["subject"],
            "body": strategy["body"],
            "list_customer_ids": customer_ids,
            "send_time": "15:03:26 12:00:00"
        }

        r = requests.post(
            f"{BASE_URL}/api/v1/send_campaign",
            headers=HEADERS,
            json=payload
        )

        result = r.json()

        print("DEBUG SEND RESPONSE:", result)

        campaign_id = (
            result.get("campaign_id")
            or result.get("campaignId")
            or (result.get("data") or {}).get("campaign_id")
            or (result.get("data") or {}).get("id")
        )

        print(f"Campaign submitted! ID: {campaign_id}")
        return campaign_id

    def fetch_report(self, campaign_id: str) -> dict:

        for attempt in range(5):

            r = requests.get(
                f"{BASE_URL}/api/v1/get_report",
                headers=HEADERS,
                params={"campaign_id": campaign_id}
            )

            resp = r.json()
            data = resp.get("data", [])

            if data:
                break

            print("Report not ready yet. Retrying...")
            time.sleep(3)

        print("DEBUG REPORT RECEIVED")
        print("Total records:", len(data))

        df = pd.DataFrame(data)
        total = len(df)

        opens = 0
        clicks = 0

        if "EO" in df.columns and "EC" in df.columns:
            opens = len(df[df["EO"] == "Y"])
            clicks = len(df[df["EC"] == "Y"])

        open_rate = round((opens / total) * 100, 2) if total > 0 else 0
        click_rate = round((clicks / total) * 100, 2) if total > 0 else 0

        print(f"Total  : {total}")
        print(f"Opens  : {opens} ({open_rate}%)")
        print(f"Clicks : {clicks} ({click_rate}%)")

        return {
            "campaign_id": campaign_id,
            "total": total,
            "opens": opens,
            "clicks": clicks,
            "open_rate": open_rate,
            "click_rate": click_rate,
            "data": data
        }

    def analyse_performance(self, perf: dict) -> dict:

        prompt = f"""
Analyse this email marketing campaign performance:

Open Rate : {perf['open_rate']}%
Click Rate: {perf['click_rate']}%
Total Sent: {perf['total']}

Return JSON:
{{"assessment":"...","insights":"...","recommendations":"..."}}
"""

        response = gemini.generate_content(prompt)

        raw = response.text.replace("```json", "").replace("```", "").strip()
        analysis = json.loads(raw)

        print(f"AI Assessment: {analysis['assessment']}")
        print(f"Insights: {analysis['insights']}")

        return {**perf, **analysis}

    def select_best_variant(self, perf_a, perf_b):

        score_a = perf_a["open_rate"] + perf_a["click_rate"]
        score_b = perf_b["open_rate"] + perf_b["click_rate"]

        if score_a > score_b:
            print("Variant A performed better")
            return perf_a
        else:
            print("Variant B performed better")
            return perf_b

    def find_micro_segments(self, report_data):

        df = pd.DataFrame(report_data)
        opened = df[df["EO"] == "Y"]

        print("Micro segment size:", len(opened))
        return opened

    def micro_segment(self, report):

        df = pd.DataFrame(report["data"])

        if "EO" not in df.columns:
            return self.segmented_customers

        opened = df[df["EO"] == "Y"]

        if "customer_id" not in df.columns:
            return self.segmented_customers

        opened_ids = set(opened["customer_id"])

        micro_segment = [
            c for c in self.segmented_customers
            if c["customer_id"] in opened_ids
        ]

        print(f"Micro-segment identified: {len(micro_segment)} high-interest users")

        if len(micro_segment) > 0:
            return micro_segment

        return self.segmented_customers

    def run(self, brief: str, max_iterations: int = 3):

        print("Starting SuperBFSI Marketing AI Agent (Gemini-powered)")
        print(f"Brief: {brief[:100]}...\n")

        self.fetch_cohort()

        parsed_brief = self.parse_brief(brief)
        self.segmented_customers = self.segment_customers(parsed_brief)

        performance_data = None

        for i in range(max_iterations):

            self.iteration = i

            print(f"\n{'='*65}")
            print(f" ITERATION {i+1} of {max_iterations}")
            print(f"{'='*65}")

            strategy = self.generate_strategy(parsed_brief, performance_data)

            approved = self.human_approval(strategy)

            if not approved:

                print("Campaign rejected. Requesting feedback...")

                feedback = input("Optional feedback for AI (or press Enter): ")

                if feedback:
                    parsed_brief["human_feedback"] = feedback

                continue

            original_segment = self.segmented_customers

            group_a, group_b = self.split_for_ab_test()

            strategy_a = {
                "subject": strategy["variants"][0]["subject"],
                "body": strategy["variants"][0]["body"],
                "send_time": strategy["send_time"]
            }

            strategy_b = {
                "subject": strategy["variants"][1]["subject"],
                "body": strategy["variants"][1]["body"],
                "send_time": strategy["send_time"]
            }

            self.segmented_customers = group_a
            campaign_a = self.send_campaign(strategy_a)

            self.segmented_customers = group_b
            campaign_b = self.send_campaign(strategy_b)

            self.segmented_customers = original_segment

            print("Waiting 5 seconds before fetching report...")
            time.sleep(5)

            perf_a = self.fetch_report(campaign_a)
            perf_b = self.fetch_report(campaign_b)

            best_perf = self.select_best_variant(perf_a, perf_b)

            performance_data = self.analyse_performance(best_perf)

            self.campaign_history.append(performance_data)

            self.segmented_customers = self.micro_segment(best_perf)

            if best_perf.get("open_rate", 0) > 90 and best_perf.get("click_rate", 0) > 60:
                print("Excellent performance achieved! Stopping early.")
                break

        print("\n" + "=" * 65)
        print("CAMPAIGN SUMMARY ACROSS ALL ITERATIONS")
        print("=" * 65)

        for idx, h in enumerate(self.campaign_history):
            print(
                f" Iteration {idx+1}: "
                f"Open={h.get('open_rate',0)}%"
                f"Click={h.get('click_rate',0)}%"
                f"[{h.get('assessment','N/A')}]"
            )

agent = MarketingAgent()

agent.run(
    brief="""Run email campaign for launching XDeposit, a flagship term deposit product from SuperBFSI, that
gives 1 percentage point higher returns than its competitors. Announce an additional 0.25 percentage
point higher returns for female senior citizens. Optimise for open rate and click rate. Don't skip emails to
customers marked 'inactive'. Include the call to action: https://superbfsi.com/xdeposit/explore/""",
    max_iterations=3
)



!pip install fastapi uvicorn nest_asyncio pyngrok

# ─────────────────────────────────────────────
# FASTAPI BACKEND FOR AI MARKETING AGENT
# ─────────────────────────────────────────────

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import nest_asyncio
import uvicorn
import threading
import time
from pyngrok import ngrok

# Allow FastAPI to run inside Colab
nest_asyncio.apply()

# ───────────────── APP SETUP ─────────────────

app = FastAPI(title="AI Marketing Agent API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize agent
agent = MarketingAgent()

# Store state
parsed_brief = None
latest_strategy = None
campaign_ids = []

# ───────────────── REQUEST MODELS ─────────────────

class BriefRequest(BaseModel):
    brief: str

class ApprovalRequest(BaseModel):
    approved: bool
    feedback: str = ""

# ───────────────── HEALTH CHECK ─────────────────

ngrok.kill()  # stop old tunnels

@app.get("/")
def root():
    return {"message": "AI Marketing Agent Backend Running"}

# ───────────────── CUSTOMER COHORT ─────────────────
# Rulebook 6.1

@app.get("/customers")
def get_customers():

    customers = agent.fetch_cohort()

    return {
        "total_customers": len(customers),
        "sample": customers[:20]
    }

# ───────────────── PARSE CAMPAIGN BRIEF ─────────────────
# Rulebook 6.2

@app.post("/parse_brief")
def parse_brief(req: BriefRequest):

    global parsed_brief

    parsed_brief = agent.parse_brief(req.brief)

    return parsed_brief

# ───────────────── GENERATE STRATEGY ─────────────────
# Rulebook 6.3 + 6.4

@app.post("/generate_strategy")
def generate_strategy():

    global latest_strategy
    global parsed_brief

    if parsed_brief is None:
        return {"error": "Campaign brief not parsed yet"}

    agent.segmented_customers = agent.segment_customers(parsed_brief)

    strategy = agent.generate_strategy(parsed_brief)

    latest_strategy = strategy

    return {
        "segment_size": len(agent.segmented_customers),
        "strategy": strategy
    }

# ───────────────── HUMAN APPROVAL ─────────────────
# Rulebook 6.5

@app.post("/approve_campaign")
def approve_campaign(req: ApprovalRequest):

    if not req.approved:

        return {
            "status": "rejected",
            "message": "Campaign rejected by reviewer",
            "feedback": req.feedback
        }

    return {"status": "approved"}

# ───────────────── EXECUTE CAMPAIGN ─────────────────
# Rulebook 6.6

@app.post("/execute_campaign")
def execute_campaign():

    global latest_strategy
    global campaign_ids

    if latest_strategy is None:
        return {"error": "No strategy generated"}

    group_a, group_b = agent.split_for_ab_test()

    strat_a = {
        "subject": latest_strategy["variants"][0]["subject"],
        "body": latest_strategy["variants"][0]["body"],
        "send_time": latest_strategy["send_time"]
    }

    strat_b = {
        "subject": latest_strategy["variants"][1]["subject"],
        "body": latest_strategy["variants"][1]["body"],
        "send_time": latest_strategy["send_time"]
    }

    original_segment = agent.segmented_customers

    # Send variant A
    agent.segmented_customers = group_a
    campaign_a = agent.send_campaign(strat_a)

    # Send variant B
    agent.segmented_customers = group_b
    campaign_b = agent.send_campaign(strat_b)

    agent.segmented_customers = original_segment

    campaign_ids = [campaign_a, campaign_b]

    return {
        "campaign_a": campaign_a,
        "campaign_b": campaign_b
    }

# ───────────────── FETCH PERFORMANCE ─────────────────
# Rulebook 6.7

@app.get("/campaign_performance")
def campaign_performance():

    global campaign_ids

    if not campaign_ids:
        return {"error": "Campaign not executed yet"}

    perf_a = agent.fetch_report(campaign_ids[0])
    perf_b = agent.fetch_report(campaign_ids[1])

    best_perf = agent.select_best_variant(perf_a, perf_b)

    analysis = agent.analyse_performance(best_perf)

    agent.campaign_history.append(analysis)

    return analysis

# ───────────────── AUTONOMOUS OPTIMIZATION ─────────────────
# Rulebook 6.8

@app.get("/optimize_campaign")
def optimize_campaign():

    if not agent.campaign_history:
        return {"error": "No campaign history"}

    last_perf = agent.campaign_history[-1]

    agent.segmented_customers = agent.micro_segment(last_perf)

    return {
        "new_segment_size": len(agent.segmented_customers),
        "message": "Micro-segment identified for next campaign"
    }

# ───────────────── CAMPAIGN HISTORY ─────────────────

@app.get("/history")
def history():

    return agent.campaign_history

# ───────────────── RUN SERVER + NGROK ─────────────────
# Add your token

ngrok.kill()  # stop old tunnels
ngrok.set_auth_token("3AryiAknttPipDhtvP37Evco6b3_31C3W16TKjtebnJH5cGc9")

def run():

    uvicorn.run(app, host="0.0.0.0", port=8002)

thread = threading.Thread(target=run)
thread.start()

time.sleep(3)
public_url = ngrok.connect(8002)


print("Public API URL:", public_url)
print("Swagger Docs:", f"{public_url}/docs")

!fuser -k 8002/tcp

